#!/usr/bin/env python3
"""
20 situation playbooks for the Upsell #1 product.
Each playbook: 2-3 pages, structured for field deployment.
"""

PLAYBOOKS = [
    # ==================== PART I: CAREER ====================
    {
        "num": 1,
        "part": "CAREER",
        "title": "THE SALARY NEGOTIATION",
        "hook": "The conversation most people bring a knife to a gunfight for.",
        "stakes": "Every dollar left on the table compounds for the rest of your career. A $15K gap at 30 is a $900K gap at 65, factoring raises and compounding.",
        "dynamics": "Your manager expects you to either undersell or oversell. They do NOT expect a calm, low-status person who knows their number, stated it once, and waited. The side that speaks first after the number loses. The side that justifies loses. The side that references their resume loses. The side that stays quiet, professional, and boring wins.",
        "tactics": [
            ("Tactic #5: The Consultant Stance", "Part I"),
            ("Tactic #11: The Strategic Pause", "Part II"),
            ("Tactic #41: The One-Line Email", "Part IV"),
        ],
        "opening": "\u201cBefore we get into numbers, I want to flag that I\u2019ve been told I\u2019m too direct in these things, so if I come across blunt, it\u2019s not intentional. Here\u2019s what I was hoping to talk about today.\u201d",
        "moves": [
            "State your number ONCE. Flat tone. No justification. \u201cBased on what I\u2019ve learned about the market and my scope, the number I\u2019m asking for is $X.\u201d Then stop talking.",
            "Let the silence after your number stretch to at least 11 seconds. They will fill it. What they fill it with is usually closer to your number than whatever they would have opened with.",
            "If they push back: \u201cI hear you. What would need to be true for this to land at $X?\u201d Puts the problem back on their side of the table.",
        ],
        "objections": [
            ("\u201cThat\u2019s above our band.\u201d",
             "\u201cI understand. What would it take to move the band? That\u2019s a conversation I\u2019d like to be part of, even if it takes a cycle.\u201d"),
            ("\u201cWe can do X instead.\u201d (a number below yours)",
             "Say nothing for 4-5 seconds. Then: \u201cI appreciate that. The number I came in with is $X. Let me take 24 hours to think about the gap and come back to you.\u201d"),
        ],
        "exit": "\u201cLet me sit with what we discussed overnight and I\u2019ll send you a short recap email tomorrow with where I landed. Does that work?\u201d",
        "mistake": "Don\u2019t explain why you\u2019re \u201cworth\u201d your number. Every word of justification is a lever they can use against you. The number is the number. Your resume is already hired.",
        "debrief": "Did I name my number first, or did I get them to? If I named it, did I then stop talking? (The second question is where most people fail, even after reading the book.)",
    },
    {
        "num": 2,
        "part": "CAREER",
        "title": "THE JOB INTERVIEW",
        "hook": "They\u2019re not interviewing you. You\u2019re interviewing each other.",
        "stakes": "The interview sets the power frame for the first 12 months of employment. Candidates who come in below end up underpaid and underleveraged. Candidates who come in as peers get the opposite.",
        "dynamics": "Every candidate performs confidence. The interviewer has seen that performance ten times this week. The differentiated candidate is quietly confident, asks real questions, and gives the interviewer moments of feeling interesting themselves. You win by making them enjoy the conversation, not by performing a script.",
        "tactics": [
            ("Tactic #5: The Consultant Stance", "Part I"),
            ("Tactic #22: The Misdirected Question", "Part II"),
            ("Tactic #33: The Reverse Qualifier", "Part III"),
        ],
        "opening": "\u201cBefore we get into my background, I read your Q3 letter this morning. You flagged the onboarding drop specifically. I\u2019d like to make sure this conversation is actually useful for that kind of problem.\u201d",
        "moves": [
            "When asked \u201ctell me about yourself,\u201d stay under 90 seconds. Most candidates go 4 minutes and lose the room by minute 2.",
            "Prepare three questions that show you thought about THEIR business, not your career. \u201cHow did the 2023 reorg affect retention of senior ICs?\u201d\u00a0beats \u201cwhat\u2019s the growth opportunity?\u201d",
            "If they ask your weakness: name a real one briefly, then name what you do about it. No performative self-deprecation.",
        ],
        "objections": [
            ("\u201cWe have several strong candidates.\u201d",
             "\u201cThat\u2019s good to hear. I\u2019d rather be chosen in a field than by default. What would make me the clear choice versus the alternatives?\u201d"),
            ("\u201cWhat\u2019s your salary expectation?\u201d (early in the process)",
             "\u201cI\u2019d rather make sure the role fits first. If we both decide we want to work together, I\u2019m confident we can land on a fair number.\u201d"),
        ],
        "exit": "\u201cThank you for the conversation. Before we wrap, what\u2019s the next step on your end, and what\u2019s the timeline you\u2019re working against?\u201d",
        "mistake": "Don\u2019t pretend you want the job more than you do. Eagerness lowers leverage. Quiet interest signals quality.",
        "debrief": "Did the interviewer leave the conversation more interested than they came in, or less? If less: what specifically bored or flattened them?",
    },
    {
        "num": 3,
        "part": "CAREER",
        "title": "THE HOSTILE BOSS / DIFFICULT MANAGER",
        "hook": "The goal is not to make them like you. It\u2019s to make them unable to hurt you.",
        "stakes": "A bad relationship with your direct manager is the single biggest predictor of whether you leave a job in the next 12 months. The conversation either resets the dynamic or confirms you\u2019re leaving.",
        "dynamics": "Hostile managers are almost always stressed up-the-chain in ways you don\u2019t see. They\u2019re not hostile because of you. You absorb it. You do NOT fix this with a heart-to-heart. You fix it by quietly shifting from \u201ctarget\u201d to \u201ctrusted channel for information they can\u2019t get elsewhere.\u201d",
        "tactics": [
            ("Tactic #4: The Assumption Audit", "Part I"),
            ("Tactic #6: The Confession First", "Part I"),
            ("Tactic #41: The One-Line Email", "Part IV"),
        ],
        "opening": "\u201cI want to set up a thirty-minute conversation with you. My goal is to get better at working with you specifically. I\u2019d like to understand where I\u2019m falling short and what would make me more useful to you.\u201d",
        "moves": [
            "Open by naming what they\u2019re probably thinking about you: \u201cYou\u2019re probably frustrated that I\u2019ve missed two deadlines. You probably think I\u2019m not senior enough for what you need. You probably wish I\u2019d just figure it out.\u201d Their guard drops.",
            "Ask ONE question and listen. \u201cWhat would the next three months look like if I was doing this well?\u201d Note the answer in front of them. The note signals seriousness.",
            "Never defend. Keep returning to: \u201cThat\u2019s fair. What would change it for you?\u201d",
        ],
        "objections": [
            ("\u201cYou should just know.\u201d",
             "\u201cI accept that. If I were going to figure it out myself, I\u2019d be wrong half the time. I\u2019d rather be aligned with you. What\u2019s the specific behavior you want different?\u201d"),
            ("\u201cI don\u2019t have time for this.\u201d",
             "\u201cThen I\u2019ll take 10 minutes instead of 30. Here\u2019s the one question: What\u2019s the one thing I could change that would matter most to you?\u201d"),
        ],
        "exit": "\u201cI\u2019ll send you a short summary of what I heard from you and what I\u2019m going to change. Can we do a follow-up in three weeks?\u201d",
        "mistake": "Don\u2019t try to change them. You are trying to change the dynamic they have with you. Those are different.",
        "debrief": "Did I leave with something specific and measurable to change? Or vague emotions? Specific wins. Vague loses.",
    },
    {
        "num": 4,
        "part": "CAREER",
        "title": "QUITTING THE JOB",
        "hook": "Resign like a pro. You\u2019ll see these people again.",
        "stakes": "Industries are small. The way you leave a job defines your reputation for the next decade, especially in tight verticals. Burn this and you burn five future jobs you don\u2019t know you wanted yet.",
        "dynamics": "Your manager will feel attacked even if you\u2019re leaving gracefully. They\u2019ll take it personally. They\u2019ll try to change your mind. They\u2019ll offer a counter. Your job is to stay warm, brief, and unmoveable. You\u2019re not negotiating. You decided.",
        "tactics": [
            ("Tactic #2: The Pre-Frame", "Part I"),
            ("Tactic #44: The Post-Agreement Bridge", "Part IV"),
            ("Tactic #41: The One-Line Email", "Part IV"),
        ],
        "opening": "\u201cI want to tell you something I\u2019ve already decided. I\u2019m going to resign. My last day is [date, giving appropriate notice]. I wanted you to hear it from me first and give you enough time to plan.\u201d",
        "moves": [
            "State the decision in the first 20 seconds. Do NOT bury it.",
            "Thank them specifically for one real thing they did for you. The real one. Not generic.",
            "Offer a concrete handoff plan. Proactive handoff > any counter offer they can make.",
        ],
        "objections": [
            ("\u201cWhat would make you stay?\u201d",
             "\u201cI appreciate that. I\u2019ve made this decision after a lot of thought. I\u2019m not looking for a counter. My last day is [date]. I want to spend the time making sure the handoff is clean.\u201d"),
            ("\u201cWe\u2019re going to give you a big raise / promotion.\u201d",
             "\u201cThat means a lot coming from you. I want you to know I\u2019m still leaving. This isn\u2019t about compensation. Let me focus on the transition.\u201d"),
        ],
        "exit": "\u201cI\u2019ll have a written transition plan to you by end of day tomorrow. Thank you for everything.\u201d Then the one-line email confirming everything in writing within 24 hours.",
        "mistake": "Don\u2019t tell them where you\u2019re going unless the relationship is genuinely good. It creates attack surface and gives them data they don\u2019t need. \u201cI\u2019m still finalizing\u201d is a complete answer.",
        "debrief": "Did I stay warm and clear, or did I slip into apologizing/over-explaining? Brief is kind; long is cruel to both of you.",
    },
    {
        "num": 5,
        "part": "CAREER",
        "title": "PITCHING YOUR BOSS ON AN IDEA",
        "hook": "The best ideas fail to people who don\u2019t know how to pitch them up the chain.",
        "stakes": "A good idea that doesn\u2019t land doesn\u2019t just stay dormant. It teaches your manager that you pitch things that don\u2019t matter. Every subsequent idea lands with lower weight.",
        "dynamics": "Your boss is thinking about their OWN priorities, not yours. The idea has to connect to something they already want to do. You\u2019re not pitching the idea. You\u2019re pitching the idea AS a path to something they already care about.",
        "tactics": [
            ("Tactic #2: The Pre-Frame", "Part I"),
            ("Tactic #16: The Preview", "Part II"),
            ("Tactic #19: The Pre-Understood Objection", "Part II"),
        ],
        "opening": "\u201cI have an idea I\u2019d like your ten minutes on. It\u2019s connected to the Q4 priority you flagged in last week\u2019s all-hands. Is now good, or should I book time?\u201d",
        "moves": [
            "Open with THEIR priority, not your idea. \u201cYou\u2019ve said the Q4 priority is onboarding retention.\u201d Then: \u201cI have a specific way to address that.\u201d",
            "Anticipate their #1 objection and name it yourself before they do: \u201cYou might think this pulls bandwidth from the launch. Here\u2019s why I don\u2019t think it does.\u201d",
            "End with a tiny ask, not a big one. \u201cCould I spend one week on a prototype and show you next Friday?\u201d One week, defined deliverable, Friday meeting.",
        ],
        "objections": [
            ("\u201cWe don\u2019t have capacity for that.\u201d",
             "\u201cUnderstood. What if I did the first week alone, on top of my current scope, and only brought in anyone else if the numbers on the prototype justify it?\u201d"),
            ("\u201cLet me think about it.\u201d",
             "\u201cFair. What specifically would you need to see to give it a yes or no? I\u2019d rather bring back exactly that than guess.\u201d"),
        ],
        "exit": "\u201cHow about I put a Friday on your calendar for a fifteen-minute demo, and if it\u2019s not going to be useful, we just cancel it that morning?\u201d",
        "mistake": "Don\u2019t pitch the idea in full. Pitch the opportunity to prove the idea. Bosses approve prototypes, not commitments.",
        "debrief": "Did I leave with a concrete next step on their calendar, or just \u201cthey\u2019re thinking about it\u201d? The former is momentum. The latter is a polite no.",
    },
    {
        "num": 6,
        "part": "CAREER",
        "title": "THE SALES DISCOVERY CALL",
        "hook": "The first call isn\u2019t a pitch. It\u2019s a diagnosis.",
        "stakes": "The first call sets the pattern for the entire relationship. Lead with features and you\u2019re a vendor forever. Lead with curiosity about their business and you\u2019re a peer from minute one.",
        "dynamics": "Most prospects have been pitched the same product four times this quarter. They\u2019re tuned for your pitch. What they\u2019re NOT tuned for is a vendor who refuses to pitch and instead asks real questions for 40 minutes. That vendor stays in their memory.",
        "tactics": [
            ("Tactic #33: The Reverse Qualifier", "Part III"),
            ("Tactic #21: The Discovery Path", "Part II"),
            ("Tactic #25: The Stakes Shift", "Part III"),
        ],
        "opening": "\u201cBefore I spend any of your time on what we do, can I ask two questions to see if we\u2019re even the right fit? If the answer is no, I\u2019d rather get you back to your day.\u201d",
        "moves": [
            "Ask how and what questions. Never why. \u201cHow are you handling that today?\u201d \u201cWhat does success look like in six months?\u201d",
            "Let every answer land for 3-4 seconds before responding. They often add more detail to fill the silence.",
            "When you hear the real pain, don\u2019t solve it yet. Ask: \u201cWhat happens if you don\u2019t solve this in the next 6 months?\u201d The cost-of-inaction answer is gold.",
        ],
        "objections": [
            ("\u201cWe\u2019re just looking right now.\u201d",
             "\u201cThat\u2019s fine. What would need to be true for you to move from looking to acting?\u201d"),
            ("\u201cSend me materials and I\u2019ll review.\u201d",
             "\u201cHappy to. Before I do, which of the things we discussed would you actually want to see proven out? That way I send you something relevant, not generic.\u201d"),
        ],
        "exit": "\u201cBased on what you\u2019ve shared, the next step I\u2019d recommend is [specific action]. Would Tuesday or Thursday next week work to continue this?\u201d",
        "mistake": "Don\u2019t answer questions they didn\u2019t ask. Over-explaining features is the #1 reason sales calls die.",
        "debrief": "How much of the call was them talking vs. me? Target ratio: 70/30 them to you. If you were over 50%, you pitched and didn\u2019t discover.",
    },

    # ==================== PART II: DATING ====================
    {
        "num": 7,
        "part": "DATING",
        "title": "THE FIRST DATE CONVERSATION",
        "hook": "Don\u2019t try to be impressive. Try to be present.",
        "stakes": "First dates are won or lost in the first 20 minutes. Most people fail by performing. The version of you that gets picked for a second date is calmer, more curious, and less trying-hard than the version you bring by default.",
        "dynamics": "Your date has expectations shaped by apps and media: that you\u2019ll interview them, perform charm, or pitch yourself. Be the rare person who does none of those. Ask real questions. Listen. Give them moments of feeling interesting.",
        "tactics": [
            ("Tactic #1: The Cold Open", "Part I"),
            ("Tactic #9: The Mirror They Don't Catch", "Part I"),
            ("Tactic #6: The Confession First", "Part I"),
        ],
        "opening": "\u201cGood to meet you. Before we sit down \u2014 have you been here before? Or is this one of those places both of us chose because it sounded neutral enough?\u201d",
        "moves": [
            "Ask two or three real questions based on something they said, not on your script. If they mention they just moved, ask what surprised them about the new city \u2014 not where they\u2019re from.",
            "Match their vulnerability level. If they share something slightly personal, match with ONE small thing. Not more.",
            "Leave 3-5 second pauses. First dates with no silence feel like interviews. First dates with calm silence feel like connection.",
        ],
        "objections": [
            ("They seem nervous or awkward:",
             "Name it gently. \u201cThese are weird by default. The first 20 minutes of any first date are structurally awkward. We can just acknowledge that and keep going.\u201d Nerves drop immediately."),
            ("They ask \u201cwhat are you looking for?\u201d early:",
             "\u201cHonestly, I\u2019m looking for someone I enjoy being around. Specifics get figured out once that\u2019s true or not. How about you?\u201d"),
        ],
        "exit": "\u201cI enjoyed this. If you did too, I\u2019d like to see you again next week. If not, I\u2019d rather know so neither of us is guessing.\u201d",
        "mistake": "Don\u2019t interview them. Questions are fine. Back-to-back questions with no reaction in between feel like a job screen.",
        "debrief": "Did they talk more than they asked? If yes, they were engaged. Did I react to what they said, or pivot back to my own talking points?",
    },
    {
        "num": 8,
        "part": "DATING",
        "title": "TURNING A DATING-APP MATCH INTO A REAL DATE",
        "hook": "The apps train you to chat forever. Every day of chatting makes the date less likely, not more.",
        "stakes": "Most matches die in endless small-talk because neither side proposes the date. The match that converts to a date within 72 hours is 3x more likely to actually meet than one that goes to day 10.",
        "dynamics": "Long chats feel safe. They\u2019re not. The longer you chat, the more the other person has invested in a fantasy version of you. Real you is never better than fantasy you. Move to real life before the fantasy cements.",
        "tactics": [
            ("Tactic #2: The Pre-Frame", "Part I"),
            ("Tactic #43: The Minimum Viable Commitment", "Part IV"),
            ("Tactic #23: The Two Doors", "Part II"),
        ],
        "opening": "\u201cI like the rhythm of this conversation more than I like the app. Would you want to grab [coffee/a drink] this week? I\u2019m around Tuesday or Thursday evening.\u201d",
        "moves": [
            "Propose the date by message 6 at the latest. If they stall past that, the match probably wasn\u2019t going to convert anyway.",
            "Specify a low-commitment format. Drinks or coffee at a specific place beats \u201clet\u2019s hang out sometime.\u201d",
            "Give two specific day options. Not seven. Not \u201cwhen are you free.\u201d Two options narrows to a yes or a clean decline.",
        ],
        "objections": [
            ("\u201cI\u2019m swamped this week, maybe next.\u201d",
             "\u201cTotally fair. What day next week usually works for you? I\u2019ll open the slot.\u201d"),
            ("\u201cLet\u2019s keep chatting first.\u201d",
             "\u201cHappy to. Honestly though, I\u2019m better in person than in text. Would you be open to 45 minutes for a drink and we keep it low-key?\u201d"),
        ],
        "exit": "\u201cPerfect. Thursday at 7 at [place]. I\u2019ll message you that morning to confirm.\u201d Then actually message that morning \u2014 reduces no-shows by 40%.",
        "mistake": "Don\u2019t keep the text conversation going for days. The longer it goes without a date proposal, the more the match slips into \u201cpen pal\u201d territory and dies.",
        "debrief": "How many messages did it take to get the date on the calendar? If over 10, I was stalling or they were. Both are information.",
    },
    {
        "num": 9,
        "part": "DATING",
        "title": "THE DEFINE-THE-RELATIONSHIP TALK",
        "hook": "If you need a DTR talk, you already know what they\u2019ll probably say. You just need to hear it.",
        "stakes": "Two months of ambiguity costs more than a direct conversation that clarifies. Most DTR conversations don\u2019t go how people fear; they go clean. The few that go badly confirm what the ambiguity was already telling you.",
        "dynamics": "The partner who initiates the DTR is rarely the one trying to control. They\u2019re the one tired of not knowing. The conversation almost always goes better than the avoidance did. The goal is not agreement. The goal is clarity about whether you\u2019re aligned.",
        "tactics": [
            ("Tactic #16: The Preview", "Part II"),
            ("Tactic #6: The Confession First", "Part I"),
            ("Tactic #11: The Strategic Pause", "Part II"),
        ],
        "opening": "\u201cI want to have a conversation with you. It\u2019s about what this is between us. I\u2019d rather know where we both stand than guess. Is now okay, or should we find a time?\u201d",
        "moves": [
            "Name YOUR position first. \u201cFor me, this is starting to feel like something I\u2019d like to keep building. I\u2019d like to know how you\u2019re reading it.\u201d",
            "Do not push them to match your position. The ask is clarity, not agreement. \u201cEven if you\u2019re in a different place, I\u2019d rather know than not know.\u201d",
            "If their answer is \u201cI don\u2019t know yet,\u201d that IS an answer. Two months in, \u201cI don\u2019t know\u201d often means \u201cnot at the level you\u2019re at.\u201d",
        ],
        "objections": [
            ("\u201cI\u2019m not ready for labels.\u201d",
             "\u201cI don\u2019t need a label. I\u2019d like to know if you\u2019re seeing other people, and whether you want this to grow or stay casual. Those are two different questions.\u201d"),
            ("\u201cI just need more time.\u201d",
             "\u201cUnderstood. When do you think you\u2019ll have a clearer sense? I\u2019m asking so I can plan my own life around what you come back with.\u201d"),
        ],
        "exit": "\u201cThank you for being honest. I\u2019m going to sit with what you said and figure out what makes sense for me. Can we talk again in a week?\u201d",
        "mistake": "Don\u2019t accept a fourth round of \u201cI need more time\u201d past about two months total. At that point you\u2019re getting your answer \u2014 it just sounds like a delay.",
        "debrief": "Did I leave with clarity, or did I let them stay ambiguous again? The point was clarity, not reassurance.",
    },
    {
        "num": 10,
        "part": "DATING",
        "title": "MEETING THE PARTNER\u2019S FAMILY",
        "hook": "They are evaluating you for ten years, not ten hours.",
        "stakes": "First impressions with a partner\u2019s family set the dynamic for decades. Bad starts can be recovered from; great starts buy you latitude you\u2019ll cash in for years.",
        "dynamics": "The family is not evaluating your career, your looks, or your wit. They\u2019re evaluating whether you\u2019re good FOR their person. They want evidence you\u2019re kind, stable, and not a project. Bring that and almost everything else is forgivable.",
        "tactics": [
            ("Tactic #1: The Cold Open", "Part I"),
            ("Tactic #15: The Third Party Story", "Part II"),
            ("Tactic #8: The Unrepayable Favor", "Part I"),
        ],
        "opening": "\u201cIt\u2019s good to finally meet you. [Partner\u2019s name] has told me real things about you \u2014 not just the safe stuff. I\u2019m glad to get to put a face to the stories.\u201d",
        "moves": [
            "At some point in the first 90 minutes, tell a specific parent ONE real thing you admire about your partner that came from them. Example: \u201cShe told me you taught her to always send thank-you cards by hand. She still does it. It\u2019s one of the small things I love about her.\u201d",
            "Ask about the family\u2019s history. Not invasive. Something they can tell a story about. Parents love being the authority on their own family.",
            "Offer to help with dishes, groceries, or the setup/cleanup. Not performatively. Just show up as someone who participates.",
        ],
        "objections": [
            ("Cold or skeptical parent:",
             "Don\u2019t try to win them over in one visit. \u201cI know this is our first time meeting. I\u2019d like to come back. I\u2019d like to earn the relationship, not fake it on one afternoon.\u201d"),
            ("Invasive question (\u201cWhat are your intentions?\u201d):",
             "\u201cFair question. Honestly, I\u2019m still figuring out how serious this is going to get. What I can tell you is that I take [partner\u2019s name] seriously, and I\u2019m treating this like something that could matter.\u201d"),
        ],
        "exit": "\u201cThank you for having me. I\u2019d like to come back. If there\u2019s anything I should do differently next time, [partner\u2019s name] can pass that along and I\u2019ll take it seriously.\u201d",
        "mistake": "Don\u2019t try to be impressive. Try to be useful and present. Impressive fades; useful and present buys you decades of good faith.",
        "debrief": "Did I leave having given them specific moments that proved I\u2019m good for their person? Or did I just get through the visit?",
    },

    # ==================== PART III: LONG-TERM RELATIONSHIPS ====================
    {
        "num": 11,
        "part": "LONG-TERM RELATIONSHIPS",
        "title": "ENDING A RECURRING FIGHT",
        "hook": "The fight isn\u2019t about what it says it\u2019s about. Solve the real thing.",
        "stakes": "Every recurring fight teaches both people that the relationship is a place where certain problems don\u2019t get resolved. Over years, this trains both partners to withhold more and more. The fight IS the problem, not just a symptom.",
        "dynamics": "The surface topic (dishes, money, his mother, her phone) is the proxy. The real topic is always one level deeper: feeling unseen, feeling controlled, feeling like effort isn\u2019t noticed. Solve the proxy, and the fight returns in six weeks under a different name. Solve the real thing, and the fight ends.",
        "tactics": [
            ("Tactic #29: The Exposed Assumption", "Part III"),
            ("Tactic #18: The Named Feeling", "Part II"),
            ("Tactic #4: The Assumption Audit", "Part I"),
        ],
        "opening": "\u201cI\u2019ve been thinking about the fight we keep having. I don\u2019t want to have it again. Can we try something different for 15 minutes?\u201d",
        "moves": [
            "Name the meta-pattern explicitly. \u201cI think we\u2019ve had this fight four times. What if we\u2019re both actually upset about something else?\u201d",
            "Go first with a genuine guess about your own underlying issue. \u201cI think for me it\u2019s that when you do [X], I feel like my effort on [Y] doesn\u2019t count. Is that landing or am I missing it?\u201d",
            "When they share theirs, validate without defending. \u201cI hear that. I wasn\u2019t seeing it. Tell me more about when you feel that.\u201d",
        ],
        "objections": [
            ("\u201cYou always do this \u2014 you try to therapy me.\u201d",
             "\u201cFair. I\u2019m not trying to. I\u2019m tired of this fight. If you\u2019ve got a better way to end it, I\u2019m in. I don\u2019t care which way we end it, just that we do.\u201d"),
            ("\u201cNothing\u2019s going to change.\u201d",
             "\u201cMaybe not. Let\u2019s agree on one specific thing each of us changes for two weeks, and if we don\u2019t feel any different, I\u2019ll drop it. Deal?\u201d"),
        ],
        "exit": "\u201cHere\u2019s what I heard I can do differently, and here\u2019s what I heard you\u2019ll try. Let\u2019s check in Sunday evening and see if anything felt different this week.\u201d",
        "mistake": "Don\u2019t re-litigate past instances. \u201cLast Tuesday you did X\u201d triggers the fight you\u2019re trying to end. Stay in the meta-pattern.",
        "debrief": "Did we both name something real underneath, or did we just negotiate the surface topic again? If surface only, the fight will be back.",
    },
    {
        "num": 12,
        "part": "LONG-TERM RELATIONSHIPS",
        "title": "THE APOLOGY / MAKING UP",
        "hook": "A good apology doesn\u2019t defend. Doesn\u2019t explain. Doesn\u2019t include \u201cbut.\u201d",
        "stakes": "Most apologies make things worse because they\u2019re actually defenses in apology clothing. A real apology costs you something \u2014 your position \u2014 and what you buy with it is the relationship returning.",
        "dynamics": "The person you hurt doesn\u2019t want explanations. They want proof that you understand specifically what you did and how it landed. They want to see that you see them. \u201cI\u2019m sorry you felt that way\u201d is the opposite of an apology. \u201cI\u2019m sorry I did X and it caused Y\u201d is an apology.",
        "tactics": [
            ("Tactic #18: The Named Feeling", "Part II"),
            ("Tactic #6: The Confession First", "Part I"),
            ("Tactic #17: The Earlier Agreement", "Part II"),
        ],
        "opening": "\u201cI owe you a real apology. Not the version I gave you yesterday. Can we sit for 10 minutes?\u201d",
        "moves": [
            "Name what you did specifically. No generalizations. \u201cI dismissed you when you told me you were struggling at work on Tuesday. I said you were overreacting. You weren\u2019t.\u201d",
            "Name how it landed for them. \u201cYou felt alone. You probably felt like I was choosing work over you. You probably wondered if I actually see what you\u2019re going through.\u201d",
            "Say what you\u2019ll do differently. Not grand promises. One specific thing. \u201cI\u2019m going to ask how your work is going on Sunday evenings. And I\u2019m going to listen without pivoting to my own day.\u201d",
        ],
        "objections": [
            ("\u201cYou always say this and nothing changes.\u201d",
             "\u201cYou\u2019re right, and I deserve that response. Which is why I\u2019m only committing to one specific thing, not everything. Let\u2019s see if I can actually do the one thing.\u201d"),
            ("\u201cI don\u2019t know if I can trust this.\u201d",
             "\u201cYou don\u2019t have to know right now. Give me time to show you with actions, not words. That\u2019s the only way trust comes back anyway.\u201d"),
        ],
        "exit": "\u201cThank you for sitting with me. I love you. I\u2019ll prove it with what I do this week, not with anything else I say tonight.\u201d",
        "mistake": "Don\u2019t use the word \u201cbut.\u201d Everything before \u201cbut\u201d gets erased. Use \u201cand\u201d or make it two sentences.",
        "debrief": "Did I apologize for something specific, or something general? If general, they can\u2019t tell what I understood, and the apology is just noise.",
    },
    {
        "num": 13,
        "part": "LONG-TERM RELATIONSHIPS",
        "title": "THE CHEATING CONFRONTATION",
        "hook": "You already know. What you need now is clarity, not confession.",
        "stakes": "The conversation either surfaces the truth in a way that lets you decide with facts, or it sends them deeper into hiding. The approach matters more than the accusation.",
        "dynamics": "Cheaters don\u2019t confess because you\u2019re angry. They confess because the cost of continued hiding becomes higher than the cost of admitting. Frontal accusation rarely works. Calm, specific, evidence-based conversation often does.",
        "tactics": [
            ("Tactic #4: The Assumption Audit", "Part I"),
            ("Tactic #11: The Strategic Pause", "Part II"),
            ("Tactic #13: The Impossible Answer", "Part II"),
        ],
        "opening": "\u201cI need to have a conversation with you. I want to go into it without accusations, but I also want honesty. Can we sit down when the kids are asleep?\u201d",
        "moves": [
            "State the specific thing you saw or felt. One thing. \u201cOn Thursday, you said you were at the gym until 9. Your phone location pinged a hotel bar at 7:30. I saw it when I opened Find My Phone.\u201d",
            "Then say nothing. Let the silence last 30 seconds. This is the single most important move.",
            "If they deflect: \u201cI\u2019m not accusing. I\u2019m asking. What\u2019s going on?\u201d Keep returning to that question.",
        ],
        "objections": [
            ("\u201cYou\u2019re imagining things.\u201d",
             "\u201cI\u2019m not willing to be gaslit. I\u2019m asking a direct question. If you want to tell me something different happened, I\u2019m listening. If you want to tell me nothing happened, I\u2019ll need you to explain the locations.\u201d"),
            ("\u201cWhy don\u2019t you trust me?\u201d",
             "\u201cThis isn\u2019t about trust in general. This is about one specific thing I saw. Tell me about that specific thing and we\u2019ll go from there.\u201d"),
        ],
        "exit": "\u201cI\u2019m not making any decisions tonight. I\u2019m going to sleep on what you told me. We can talk more tomorrow.\u201d",
        "mistake": "Don\u2019t confront without evidence you can point to. Confronting on a hunch gives them the high ground and lets them make YOU the problem.",
        "debrief": "Did I get specifics or did I get deflections? Deflections are usually answers. If they refused to name Thursday night specifically, I already know.",
    },
    {
        "num": 14,
        "part": "LONG-TERM RELATIONSHIPS",
        "title": "THE \u201cI NEED SPACE\u201d CONVERSATION",
        "hook": "Ask for space the right way and you come back stronger. Ask for it the wrong way and it becomes a breakup.",
        "stakes": "How you ask for space determines whether it\u2019s a pause or a slow ending. Most \u201cI need space\u201d conversations accidentally sound like rejection and trigger the partner into accelerating the ending you didn\u2019t want.",
        "dynamics": "The partner hears \u201cI need space\u201d as \u201cI want to leave.\u201d The more you assure them it\u2019s not, the less they believe you. The fix is to be specific about what space means, for how long, and what you want afterwards.",
        "tactics": [
            ("Tactic #2: The Pre-Frame", "Part I"),
            ("Tactic #16: The Preview", "Part II"),
            ("Tactic #39: The Waiting Period", "Part IV"),
        ],
        "opening": "\u201cI want to tell you something that might sound bad at first. It\u2019s not what it sounds like. Can I explain the whole thing before you react?\u201d",
        "moves": [
            "Be specific. \u201cI want two weeks where we don\u2019t see each other daily. I\u2019d still like to text and talk on the phone. I\u2019m not leaving. I\u2019m trying to come back as a better version of myself.\u201d",
            "Name the fear they\u2019re having. \u201cYou\u2019re probably hearing this as me wanting to leave. It\u2019s not. Here\u2019s why I know it\u2019s not.\u201d",
            "Offer a concrete check-in point. \u201cTwo weeks from today, I want us to have dinner and talk about how it went.\u201d",
        ],
        "objections": [
            ("\u201cIf you need space from me, we should just break up.\u201d",
             "\u201cI don\u2019t want that. Let me be specific about what I\u2019m asking for and what I\u2019m not. If after two weeks you think we should break up, I\u2019ll respect that. But I\u2019m not asking for a breakup today.\u201d"),
            ("\u201cThis is just going to make it worse.\u201d",
             "\u201cMaybe. It\u2019s a risk. The alternative is I stay and keep being the version of me that isn\u2019t working. I\u2019d rather come back better than stay broken.\u201d"),
        ],
        "exit": "\u201cThank you for listening. Two weeks from today. Same time. Let\u2019s put it in the calendar before I leave tonight.\u201d",
        "mistake": "Don\u2019t leave it open-ended. \u201cI need some time\u201d with no end date destroys the relationship through uncertainty. Specific time bounds preserve it.",
        "debrief": "Did I leave with a concrete return date they agreed to? If no, I just initiated a breakup without meaning to.",
    },

    # ==================== PART IV: ENDINGS & RECOVERY ====================
    {
        "num": 15,
        "part": "ENDINGS & RECOVERY",
        "title": "INITIATING A BREAKUP",
        "hook": "Be the person you\u2019d want on the other side of this.",
        "stakes": "How you break up affects the other person for months or years. It also defines who YOU are, which will show up in every future relationship. Doing this well is a kindness to both of you.",
        "dynamics": "The other person will beg, bargain, get angry, cry, or all four. Your job is to stay warm, clear, and final. Every time you soften, you extend the pain. A clear no delivered kindly is the most merciful thing you can offer.",
        "tactics": [
            ("Tactic #2: The Pre-Frame", "Part I"),
            ("Tactic #37: The Unclosing", "Part IV"),
            ("Tactic #11: The Strategic Pause", "Part II"),
        ],
        "opening": "\u201cI\u2019ve been thinking a lot about us. I need to tell you where I\u2019ve landed. It\u2019s not what either of us wanted. I don\u2019t think we should keep going.\u201d",
        "moves": [
            "State the decision clearly in the first 30 seconds. Do not bury it in preamble. The burial is worse than the news.",
            "Name one specific real reason, not a list. \u201cFor me, it\u2019s [specific thing]. I\u2019ve sat with it for a long time. I don\u2019t see it changing.\u201d",
            "Do not argue. \u201cI hear you. I\u2019m not going to change my mind. I\u2019m sorry.\u201d Return to that sentence as many times as needed.",
        ],
        "objections": [
            ("\u201cLet\u2019s try couples therapy.\u201d",
             "\u201cI\u2019m past where therapy would help. I thought about it. I don\u2019t want to put both of us through months of trying when I already know.\u201d"),
            ("\u201cWhat did I do? Tell me and I\u2019ll change.\u201d",
             "\u201cYou didn\u2019t do something wrong. This isn\u2019t about a mistake I\u2019m angry about. It\u2019s about me knowing this isn\u2019t the life I want. I\u2019m sorry.\u201d"),
        ],
        "exit": "\u201cI\u2019ll give you space tonight. I\u2019m going to stay at [place]. We can figure out the practical stuff this weekend. I\u2019m not going to disappear. I\u2019m going to do this as well as I can.\u201d",
        "mistake": "Don\u2019t have the breakup at a restaurant, on a holiday, before a trip, or in a moving car. Home. Private. With time afterward for them to react.",
        "debrief": "Did I stay clear and kind, or did I let them argue me into softness I didn\u2019t mean? Softness now is cruelty later.",
    },
    {
        "num": 16,
        "part": "ENDINGS & RECOVERY",
        "title": "BEING DUMPED (THE FINAL CONVERSATION)",
        "hook": "You can\u2019t win the breakup. You can leave it with your dignity.",
        "stakes": "The conversation where you get broken up with determines how you remember yourself for years. Begging prolongs nothing but makes the memory worse. Dignity doesn\u2019t get them back, but it makes the healing faster.",
        "dynamics": "They\u2019ve been thinking about this for weeks. You\u2019re hearing it for the first time. They\u2019re prepared. You\u2019re not. Your job is not to change their mind in one conversation. Your job is to hear them, ask the two questions that actually matter, and leave with your dignity intact.",
        "tactics": [
            ("Tactic #11: The Strategic Pause", "Part II"),
            ("Tactic #39: The Waiting Period", "Part IV"),
            ("Tactic #47: The Last-Word Exit", "Part IV"),
        ],
        "opening": "(They have spoken. You have heard them.) \u201cOkay. I hear you. Can I ask you one or two questions before we wrap this up?\u201d",
        "moves": [
            "Pause before responding. Don\u2019t react in the first 10 seconds. Your first instinct will be to argue, beg, or bargain. All three are mistakes.",
            "Ask the two questions that actually matter: \u201cIs there anything I could do to change this?\u201d (listen to the real answer) and \u201cAre you sure?\u201d (one time only).",
            "If they say it\u2019s final: \u201cI don\u2019t agree with your decision. I respect it. I\u2019m going to take time to process. Please give me that space.\u201d",
        ],
        "objections": [
            ("They\u2019re explaining at length and want you to understand:",
             "Let them talk. Don\u2019t interrupt. Your silence is dignified, not weak. When they finish, acknowledge: \u201cI hear what you\u2019re saying. I don\u2019t have to agree with it to respect it.\u201d"),
            ("They want to stay friends immediately:",
             "\u201cMaybe. Not now. I need distance first. If there\u2019s friendship later, it has to come after time. Not instead of grieving.\u201d"),
        ],
        "exit": "\u201cI\u2019m going to leave now. I\u2019m not going to call or text for at least two weeks. I wish you well. I need to go.\u201d Then actually leave. Don\u2019t linger.",
        "mistake": "Don\u2019t beg. Don\u2019t bargain. Don\u2019t promise to change. Don\u2019t ask to \u201ctalk about it more tomorrow.\u201d Those moves don\u2019t get them back; they just extend the pain and cost you your self-respect.",
        "debrief": "Did I leave with my dignity, or did I beg? Dignity now is the foundation for whatever comes next \u2014 either getting them back months later, or healing faster so you can move on.",
    },
    {
        "num": 17,
        "part": "ENDINGS & RECOVERY",
        "title": "GETTING AN EX BACK",
        "hook": "If this works, it\u2019s not because of one conversation. It\u2019s because of who you became while they were gone.",
        "stakes": "Most attempts to get an ex back fail because people rush. Timing matters more than words. The right conversation at the wrong time closes the door. The wrong conversation at the right time still works.",
        "dynamics": "Your ex needs to SEE you\u2019ve changed, not hear you claim it. The conversation works when it happens at least 60-90 days after the breakup, after no-contact, after you\u2019ve genuinely done the work you said you would. Before that, nothing works.",
        "tactics": [
            ("Tactic #1: The Cold Open", "Part I"),
            ("Tactic #6: The Confession First", "Part I"),
            ("Tactic #39: The Waiting Period", "Part IV"),
        ],
        "opening": "\u201cI\u2019ve thought about whether to reach out for a while. I don\u2019t want to pull you back into anything you\u2019re not ready for. I just wanted to say hi and see how you\u2019re doing. No pressure to write back.\u201d",
        "moves": [
            "First contact by text, not call. Low-pressure, easy to ignore, easy to respond to if they want to.",
            "Don\u2019t reference the breakup directly in the first exchange. Talk about something specific from your actual life. Something that shows you\u2019ve been doing something, not pining.",
            "If they respond warmly after a few exchanges, propose a LOW-STAKES meet-up: coffee, a walk, something with a clear end time. Not dinner. Not alcohol. Not emotional.",
        ],
        "objections": [
            ("\u201cI don\u2019t think we should talk.\u201d",
             "\u201cI understand. I\u2019m not going to push. If that changes for you, I\u2019m here. Take care.\u201d Then actually stop. Do not text again."),
            ("\u201cAre you trying to get back together?\u201d (early):",
             "\u201cHonestly \u2014 I don\u2019t know yet. I wanted to see you and see what\u2019s real, not decide in advance. Is that okay?\u201d"),
        ],
        "exit": "\u201cThis was good. I\u2019m glad we did this. Let me give you time to figure out what you want. I\u2019ll wait for you to reach out next.\u201d",
        "mistake": "Don\u2019t make the first conversation heavy. Your job is to show them who you\u2019ve become, not to relitigate who you were. If there\u2019s a future, it comes from light conversations, not intense ones.",
        "debrief": "Did I show or did I tell? Showing who I am now is what might bring them back. Telling them I\u2019ve changed triggers their detector and confirms their decision.",
    },

    # ==================== PART V: FAMILY & LIFE ====================
    {
        "num": 18,
        "part": "FAMILY & LIFE",
        "title": "RECONCILIATION WITH ESTRANGED FAMILY",
        "hook": "The longer the silence, the smaller the first step should be.",
        "stakes": "Ten years of estrangement from a parent, sibling, or adult child doesn\u2019t heal in one conversation. But one conversation handled right can open a door that was shut. Handled wrong, it slams harder.",
        "dynamics": "Estranged family members have built their identity around the estrangement. Their brain has defended it to themselves for years. Direct reconciliation attempts fire their detector instantly. Indirect, low-pressure, small-signal openings work.",
        "tactics": [
            ("Tactic #1: The Cold Open", "Part I"),
            ("Tactic #6: The Confession First", "Part I"),
            ("Tactic #8: The Unrepayable Favor", "Part I"),
        ],
        "opening": "(At a wedding, funeral, or family event where you\u2019ll naturally see them.) \u201cThat was a nice ceremony. Did you drive up or fly?\u201d",
        "moves": [
            "Do not open with the estrangement. Do not apologize in the first conversation. Do not try to \u201cresolve\u201d anything. The opening conversation is about establishing that normal speech between you is possible.",
            "Keep the first conversation under 10 minutes. Leave before they feel you want too much.",
            "If they seem receptive, leave with a specific low-stakes ask: \u201cIt was good to talk. Can I call you sometime? I won\u2019t make it weird. Just a normal conversation every couple of months.\u201d",
        ],
        "objections": [
            ("They refuse to engage:",
             "\u201cThat\u2019s fair. I understand. I\u2019m here if that ever changes. I won\u2019t keep pushing.\u201d Then don\u2019t. The door stays open because you didn\u2019t force it."),
            ("\u201cWhat do you want?\u201d",
             "\u201cHonestly, just to talk. I\u2019ve missed the normal stuff. I\u2019m not trying to litigate anything from before. I just don\u2019t want us to be strangers.\u201d"),
        ],
        "exit": "\u201cIt was good to see you. I hope we can do this more. Take care of yourself.\u201d Then leave the conversation. Don\u2019t push for more than they\u2019re ready for.",
        "mistake": "Don\u2019t apologize for the whole estrangement in the first conversation. It overwhelms them and triggers the defenses they\u2019ve built. Earn a second conversation first. The apology comes at conversation 3 or 4.",
        "debrief": "Did I leave the door more open than I found it? Or did I push and get it shut harder? Small, patient moves compound.",
    },
    {
        "num": 19,
        "part": "FAMILY & LIFE",
        "title": "CUSTODY / DIVORCE MEDIATION",
        "hook": "Mediation rewards the person who stays calm and prepared. Every time.",
        "stakes": "The custody and financial arrangements from mediation define your life and your kids\u2019 lives for decades. Every percentage point you give up because you got emotional costs real years and real money.",
        "dynamics": "The mediator is not your friend. They are not your ex\u2019s friend. Their job is to produce an agreement, not a fair one. The person who stays calmest, cites specifics, and refuses to escalate wins every contested point. Emotion is poison. Preparation is leverage.",
        "tactics": [
            ("Tactic #4: The Assumption Audit", "Part I"),
            ("Tactic #19: The Pre-Understood Objection", "Part II"),
            ("Tactic #11: The Strategic Pause", "Part II"),
        ],
        "opening": "(To the mediator, not to your ex.) \u201cThank you for your time. My goals today are [two specific things]. I\u2019ve brought documentation to support my position. I\u2019m prepared to be flexible where we can find fair compromise.\u201d",
        "moves": [
            "Bring a written document with your three non-negotiables. Hand a copy to the mediator. Specifics on paper carry weight that verbal claims don\u2019t.",
            "When your ex makes an accusation, do NOT defend. Say: \u201cThat doesn\u2019t match my understanding. I have records showing [X]. Can I share them?\u201d",
            "Use silence. When a proposal is made that you don\u2019t agree with, count to 8 silently. Most of the time the proposer either improves it or clarifies.",
        ],
        "objections": [
            ("Your ex attacks your character:",
             "\u201cI\u2019m not going to respond to that here. I\u2019d like to return to the specific issue we\u2019re deciding on. Which was [X].\u201d"),
            ("The mediator pushes for a compromise you don\u2019t want:",
             "\u201cI hear the value in compromise. On this specific issue, I don\u2019t have flexibility for the reasons I\u2019ve documented. I\u2019d like to set this aside and come back to it if there\u2019s room after the others.\u201d"),
        ],
        "exit": "\u201cThank you. I\u2019ll review the proposed terms with my attorney before signing anything. I\u2019ll have a response to you by [specific date].\u201d",
        "mistake": "Don\u2019t sign anything in the room. Every mediator will tell you \u201cwe\u2019re so close, let\u2019s just finalize.\u201d 24 hours of sleep on contested terms has saved more custody agreements than any negotiation tactic.",
        "debrief": "Did I stay regulated, or did I escalate when pushed? Every escalation cost me leverage. Calm is the single most valuable thing you bring.",
    },
    {
        "num": 20,
        "part": "FAMILY & LIFE",
        "title": "THE CONTRACTOR / SERVICE DISPUTE",
        "hook": "Most overcharges collapse when you stop talking.",
        "stakes": "A typical contractor or service dispute is $500-$15,000. The difference between handling it well and handling it badly is 2-10x that dispute value.",
        "dynamics": "Contractors who overcharge are counting on one of three things: you\u2019ll pay to avoid conflict, you\u2019ll get emotional and look unreasonable, or you\u2019ll accept their explanation at face value. The winning move is calm, specific, documented, and silent at the right moments.",
        "tactics": [
            ("Tactic #11: The Strategic Pause", "Part II"),
            ("Tactic #13: The Impossible Answer", "Part II"),
            ("Tactic #41: The One-Line Email", "Part IV"),
        ],
        "opening": "\u201cThanks for the invoice. I looked through it and there\u2019s a gap between the estimate and the final number I want to understand. Specifically, line item 4 went from $3,200 to $13,500. Can you walk me through what happened there?\u201d",
        "moves": [
            "Ask them to explain the overage. Then say NOTHING while they explain. Count to 11 after they finish. Most contractors improve the number during that silence without you having to push.",
            "If they don\u2019t improve it: \u201cI want to pay you fairly for work you actually did. What I\u2019m not willing to do is pay for a number that doubled without a change order I signed. What would it take to land on something we both think is fair?\u201d",
            "Put everything in writing. \u201cCan you email me the revised invoice and the breakdown? I want to make sure we\u2019re aligned before I pay.\u201d",
        ],
        "objections": [
            ("\u201cThat\u2019s just what it cost.\u201d",
             "\u201cI hear you. I don\u2019t have the documentation to support paying four times the estimate without a change order. Can you send me what justifies it, so I have records?\u201d Silence after."),
            ("\u201cI\u2019m going to put a lien on your property.\u201d",
             "\u201cLet\u2019s not go there. I\u2019d rather find a number that works for both of us. What\u2019s the real number you\u2019d accept to call this done today?\u201d"),
        ],
        "exit": "\u201cLet me think about what you shared. I\u2019ll have a response to you by end of day tomorrow. In the meantime, please don\u2019t do additional work.\u201d Then follow up in writing with the agreed number.",
        "mistake": "Don\u2019t get emotional. Don\u2019t threaten lawsuits. Don\u2019t demand immediate answers. Calm, specific, and slow wins every dispute I\u2019ve ever documented.",
        "debrief": "What did the contractor say in the silence after my first calm question? That\u2019s usually where the real number lives.",
    },
]
