'use client';

import { motion } from 'framer-motion';
import { useInView } from 'react-intersection-observer';

const conversation = [
  { speaker: 'SELLER', text: "The final price for the package is $50,000. This is a one-time offer." },
  { speaker: 'BUYER', text: "That's much higher than I expected. Let me think about it." },
  { speaker: 'SELLER', text: "I have two other potential buyers ready to close this week. The offer expires Friday." },
  { speaker: '[ 48 HOURS OF SILENCE ]', text: "..." },
  { speaker: 'BUYER', text: "Okay, I'm in. How do we proceed?" },
];

const annotations = [
  { text: 'ANCHORING DETECTED', line: 0 },
  { text: 'SCARCITY FRAME', line: 2 },
  { text: 'SOCIAL PROOF', line: 2 },
  { text: 'VOID PULL', line: 3 },
];


const InfluenceDecoder = () => {
  const { ref, inView } = useInView({ triggerOnce: true, threshold: 0.3 });

  return (
    <section ref={ref} className="relative py-16">
      <div className="text-left mb-12">
        <h2 className="font-mono text-sm uppercase tracking-widest text-gray-500">
          EXHIBIT D: INFLUENCE DECODER
        </h2>
        <p className="text-3xl mt-2">Field Analysis</p>
      </div>

      <div className="relative border-2 border-gray-400 bg-[#F4ECD8] p-6 sm:p-8 shadow-lg">
        <div className="space-y-6 font-special-elite text-lg text-gray-900">
          {conversation.map((msg, index) => (
            <motion.div 
              key={index} 
              className="grid grid-cols-[100px_1fr] gap-4 items-center relative"
              initial={{opacity: 0}}
              animate={inView ? {opacity: 1} : {}}
              transition={{duration: 0.5, delay: index * 0.5}}
            >
              <div className="font-mono text-sm pt-1">{msg.speaker}:</div>
              <p className={`leading-relaxed ${msg.speaker.startsWith('[') && 'text-gray-500 italic'}`}>{msg.text}</p>

              {annotations.filter(a => a.line === index).map((a, aIndex) => (
                 <motion.div 
                    key={aIndex} 
                    className="absolute -right-4 top-1/2 flex items-center"
                    initial={{opacity: 0, x: -20}}
                    animate={inView ? {opacity: 1, x: 0} : {}}
                    transition={{duration: 0.5, delay: (conversation.length + aIndex) * 0.5}}
                  >
                    <div className="w-8 border-t-2 border-dashed border-red-500"></div>
                    <div className="bg-red-500 text-white text-xs font-mono uppercase px-2 py-1 rounded-sm shadow-md">{a.text}</div>
                 </motion.div>
              ))}

            </motion.div>
          ))}
        </div>
        <p className="text-center mt-12 font-mono text-xs text-gray-500 uppercase tracking-wider">
            Analysis generated by Shadow Persuasion AI Visual Intelligence Module
        </p>
      </div>
    </section>
  );
};

export default InfluenceDecoder;
