'use client';

const conversation = [
  { speaker: 'SELLER', text: "The final price for the package is $50,000. This is a one-time offer." },
  { speaker: 'BUYER', text: "That's much higher than I expected. Let me think about it." },
  { speaker: 'SELLER', text: "I have two other potential buyers ready to close this week. The offer expires Friday." },
  { speaker: '[ 48 HOURS OF SILENCE ]', text: "..." },
  { speaker: 'BUYER', text: "Okay, I'm in. How do we proceed?" },
];

const annotations = [
  { text: 'ANCHORING DETECTED', line: 0 },
  { text: 'SOCIAL PROOF + SCARCITY FRAME', line: 2 },
  { text: 'VOID PULL', line: 3 },
];

const InfluenceDecoder = () => {
  return (
    <section className="relative bg-[#EDE3D0] rounded-lg p-8 md:p-12">
      <div className="text-center mb-12">
        <h2 className="font-mono text-sm uppercase tracking-widest text-gray-500">
          INFLUENCE DECODER
        </h2>
        <p className="text-3xl mt-2 text-black">Field Analysis</p>
        <p className="text-gray-600 mt-2 text-base">Every conversation has hidden tactics. Our AI flags them in real time.</p>
      </div>

      <div className="relative border-2 border-gray-400 bg-[#F4ECD8] p-6 sm:p-8 shadow-lg max-w-4xl mx-auto">
        <div className="space-y-6 font-special-elite text-lg text-gray-900">
          {conversation.map((msg, index) => (
            <div
              key={index}
              className="grid grid-cols-1 md:grid-cols-[140px_1fr] gap-1 md:gap-4 items-start"
            >
              <div className="font-mono text-sm pt-1 font-bold md:font-normal">{msg.speaker}:</div>
              <div>
                <p className={`leading-relaxed ${msg.speaker.startsWith('[') ? 'text-gray-500 italic' : ''}`}>{msg.text}</p>

                {annotations.filter(a => a.line === index).map((a, aIndex) => (
                  <div key={aIndex} className="flex items-center mt-2">
                    <div className="w-8 border-t-2 border-dashed border-red-500" />
                    <div className="bg-red-500 text-white text-xs font-mono uppercase px-2 py-1 rounded-sm shadow-md">{a.text}</div>
                  </div>
                ))}
              </div>
            </div>
          ))}
        </div>
        <p className="text-center mt-12 font-mono text-xs text-gray-500 uppercase tracking-wider">
          Analysis generated by Shadow Persuasion Conversation Analyzer
        </p>
      </div>
    </section>
  );
};

export default InfluenceDecoder;
